export interface SunPhasesResponse {
  solarNoon: string | null,
  nadir: string | null,
  sunrise: string | null,
  sunset: string | null,
  sunriseEnd: string | null,
  sunsetStart: string | null,
  dawn: string | null,
  dusk: string | null,
  nauticalDawn: string | null,
  nauticalDusk: string | null,
  nightEnd: string | null,
  night: string | null,
  goldenHourEnd: string | null,
  goldenHour: string | null,
}
